/* Generated by dx imports sync. */
/* Source-owned IDE contract for DX WWW auto-imports. */

declare module "#components" {
  export { ArrangePanel } from "../../components/whiteboard/arrange-panel";
  export { CanvasStage } from "../../components/whiteboard/canvas-stage";
  export { ConnectorInfo } from "../../components/whiteboard/connector-info";
  export { createDemoWhiteboardDocument } from "../../components/whiteboard/demo-document";
  export { DocumentPanel } from "../../components/whiteboard/document-panel";
  export { ExportPanel } from "../../components/whiteboard/export-panel";
  export { ImportPanel } from "../../components/whiteboard/import-panel";
  export { WhiteboardApp } from "../../components/whiteboard/index";
  export { FILL_SWATCHES, STROKE_SWATCHES } from "../../components/whiteboard/inspector-options";
  export { Inspector } from "../../components/whiteboard/inspector";
  export { LibraryPanel } from "../../components/whiteboard/library-panel";
  export { MeasurementPanel } from "../../components/whiteboard/measurement-panel";
  export { MinimapPanel } from "../../components/whiteboard/minimap-panel";
  export { NumberField } from "../../components/whiteboard/number-field";
  export { OutlinePanel } from "../../components/whiteboard/outline-panel";
  export { PresentationPanel } from "../../components/whiteboard/presentation-panel";
  export { SharePanel } from "../../components/whiteboard/share-panel";
  export { StatusBar } from "../../components/whiteboard/status-bar";
  export { SvgStagePreview } from "../../components/whiteboard/svg-stage-preview";
  export { TextControls } from "../../components/whiteboard/text-controls";
  export { TextEditorOverlay } from "../../components/whiteboard/text-editor-overlay";
  export { DxIcon, Toolbar } from "../../components/whiteboard/toolbar";
  export { WhiteboardApp } from "../../components/whiteboard/whiteboard-app";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare module "#imports" {
  export { ArrangePanel } from "../../components/whiteboard/arrange-panel";
  export { CanvasStage } from "../../components/whiteboard/canvas-stage";
  export { ConnectorInfo } from "../../components/whiteboard/connector-info";
  export { createDemoWhiteboardDocument } from "../../components/whiteboard/demo-document";
  export { DocumentPanel } from "../../components/whiteboard/document-panel";
  export { ExportPanel } from "../../components/whiteboard/export-panel";
  export { ImportPanel } from "../../components/whiteboard/import-panel";
  export { WhiteboardApp } from "../../components/whiteboard/index";
  export { FILL_SWATCHES, STROKE_SWATCHES } from "../../components/whiteboard/inspector-options";
  export { Inspector } from "../../components/whiteboard/inspector";
  export { LibraryPanel } from "../../components/whiteboard/library-panel";
  export { MeasurementPanel } from "../../components/whiteboard/measurement-panel";
  export { MinimapPanel } from "../../components/whiteboard/minimap-panel";
  export { NumberField } from "../../components/whiteboard/number-field";
  export { OutlinePanel } from "../../components/whiteboard/outline-panel";
  export { PresentationPanel } from "../../components/whiteboard/presentation-panel";
  export { SharePanel } from "../../components/whiteboard/share-panel";
  export { StatusBar } from "../../components/whiteboard/status-bar";
  export { SvgStagePreview } from "../../components/whiteboard/svg-stage-preview";
  export { TextControls } from "../../components/whiteboard/text-controls";
  export { TextEditorOverlay } from "../../components/whiteboard/text-editor-overlay";
  export { DxIcon, Toolbar } from "../../components/whiteboard/toolbar";
  export { WhiteboardApp } from "../../components/whiteboard/whiteboard-app";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare global {
  const ArrangePanel: typeof import("../../components/whiteboard/arrange-panel")["ArrangePanel"];
  const CanvasStage: typeof import("../../components/whiteboard/canvas-stage")["CanvasStage"];
  const serializeCanvasStage: typeof import("../../components/whiteboard/canvas-stage")["serializeCanvasStage"];
  const ConnectorInfo: typeof import("../../components/whiteboard/connector-info")["ConnectorInfo"];
  const createDemoWhiteboardDocument: typeof import("../../components/whiteboard/demo-document")["createDemoWhiteboardDocument"];
  const DocumentPanel: typeof import("../../components/whiteboard/document-panel")["DocumentPanel"];
  const ExportPanel: typeof import("../../components/whiteboard/export-panel")["ExportPanel"];
  const ImportPanel: typeof import("../../components/whiteboard/import-panel")["ImportPanel"];
  const WhiteboardApp: typeof import("../../components/whiteboard/index")["WhiteboardApp"];
  const FILL_SWATCHES: typeof import("../../components/whiteboard/inspector-options")["FILL_SWATCHES"];
  const STROKE_SWATCHES: typeof import("../../components/whiteboard/inspector-options")["STROKE_SWATCHES"];
  const Inspector: typeof import("../../components/whiteboard/inspector")["Inspector"];
  const LibraryPanel: typeof import("../../components/whiteboard/library-panel")["LibraryPanel"];
  const MeasurementPanel: typeof import("../../components/whiteboard/measurement-panel")["MeasurementPanel"];
  const MinimapPanel: typeof import("../../components/whiteboard/minimap-panel")["MinimapPanel"];
  const NumberField: typeof import("../../components/whiteboard/number-field")["NumberField"];
  const OutlinePanel: typeof import("../../components/whiteboard/outline-panel")["OutlinePanel"];
  const PresentationPanel: typeof import("../../components/whiteboard/presentation-panel")["PresentationPanel"];
  const SharePanel: typeof import("../../components/whiteboard/share-panel")["SharePanel"];
  const StatusBar: typeof import("../../components/whiteboard/status-bar")["StatusBar"];
  const SvgStagePreview: typeof import("../../components/whiteboard/svg-stage-preview")["SvgStagePreview"];
  const TextControls: typeof import("../../components/whiteboard/text-controls")["TextControls"];
  const TextEditorOverlay: typeof import("../../components/whiteboard/text-editor-overlay")["TextEditorOverlay"];
  const DxIcon: typeof import("../../components/whiteboard/toolbar")["DxIcon"];
  const Toolbar: typeof import("../../components/whiteboard/toolbar")["Toolbar"];
  const WhiteboardApp: typeof import("../../components/whiteboard/whiteboard-app")["WhiteboardApp"];
  const Icon: typeof import("../../components/icons/icon")["Icon"];
}

export {};
