/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "./whiteboard/arrange-panel";
export * from "./whiteboard/canvas-stage";
export * from "./whiteboard/connector-info";
export * from "./whiteboard/demo-document";
export * from "./whiteboard/document-panel";
export * from "./whiteboard/export-panel";
export * from "./whiteboard/import-panel";
export * from "./whiteboard/index";
export * from "./whiteboard/inspector-options";
export * from "./whiteboard/inspector";
export * from "./whiteboard/library-panel";
export * from "./whiteboard/measurement-panel";
export * from "./whiteboard/minimap-panel";
export * from "./whiteboard/number-field";
export * from "./whiteboard/outline-panel";
export * from "./whiteboard/presentation-panel";
export * from "./whiteboard/share-panel";
export * from "./whiteboard/status-bar";
export * from "./whiteboard/svg-stage-preview";
export * from "./whiteboard/text-controls";
export * from "./whiteboard/text-editor-overlay";
export * from "./whiteboard/toolbar";
export * from "./whiteboard/whiteboard-app";
export * from "./icons/icon";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "ArrangePanel",
      "source": "components/whiteboard/arrange-panel.tsx",
      "import_path": "@/components/whiteboard/arrange-panel",
      "barrel_export": "./whiteboard/arrange-panel",
      "exports": [
        "ArrangePanel",
        "ArrangePanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "ArrangePanel"
      ],
      "unused_exports": [
        "ArrangePanelProps"
      ],
      "type_exports": [
        "ArrangePanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "CanvasStage",
      "source": "components/whiteboard/canvas-stage.tsx",
      "import_path": "@/components/whiteboard/canvas-stage",
      "barrel_export": "./whiteboard/canvas-stage",
      "exports": [
        "CanvasStage",
        "serializeCanvasStage"
      ],
      "default_export_name": null,
      "used_exports": [
        "CanvasStage"
      ],
      "unused_exports": [
        "serializeCanvasStage"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ConnectorInfo",
      "source": "components/whiteboard/connector-info.tsx",
      "import_path": "@/components/whiteboard/connector-info",
      "barrel_export": "./whiteboard/connector-info",
      "exports": [
        "ConnectorInfo",
        "ConnectorInfoProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "ConnectorInfo"
      ],
      "unused_exports": [
        "ConnectorInfoProps"
      ],
      "type_exports": [
        "ConnectorInfoProps"
      ]
    },
    {
      "kind": "component",
      "name": "createDemoWhiteboardDocument",
      "source": "components/whiteboard/demo-document.ts",
      "import_path": "@/components/whiteboard/demo-document",
      "barrel_export": "./whiteboard/demo-document",
      "exports": [
        "createDemoWhiteboardDocument"
      ],
      "default_export_name": null,
      "used_exports": [
        "createDemoWhiteboardDocument"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "DocumentPanel",
      "source": "components/whiteboard/document-panel.tsx",
      "import_path": "@/components/whiteboard/document-panel",
      "barrel_export": "./whiteboard/document-panel",
      "exports": [
        "DocumentPanel",
        "DocumentPanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "DocumentPanel"
      ],
      "unused_exports": [
        "DocumentPanelProps"
      ],
      "type_exports": [
        "DocumentPanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "ExportPanel",
      "source": "components/whiteboard/export-panel.tsx",
      "import_path": "@/components/whiteboard/export-panel",
      "barrel_export": "./whiteboard/export-panel",
      "exports": [
        "ExportPanel",
        "ExportPanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "ExportPanel"
      ],
      "unused_exports": [
        "ExportPanelProps"
      ],
      "type_exports": [
        "ExportPanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "ImportPanel",
      "source": "components/whiteboard/import-panel.tsx",
      "import_path": "@/components/whiteboard/import-panel",
      "barrel_export": "./whiteboard/import-panel",
      "exports": [
        "ImportPanel",
        "ImportPanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "ImportPanel"
      ],
      "unused_exports": [
        "ImportPanelProps"
      ],
      "type_exports": [
        "ImportPanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "WhiteboardApp",
      "source": "components/whiteboard/index.ts",
      "import_path": "@/components/whiteboard/index",
      "barrel_export": "./whiteboard/index",
      "exports": [
        "WhiteboardApp"
      ],
      "default_export_name": null,
      "used_exports": [
        "WhiteboardApp"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "FILL_SWATCHES",
      "source": "components/whiteboard/inspector-options.ts",
      "import_path": "@/components/whiteboard/inspector-options",
      "barrel_export": "./whiteboard/inspector-options",
      "exports": [
        "FILL_SWATCHES",
        "InspectorSwatch",
        "STROKE_SWATCHES"
      ],
      "default_export_name": null,
      "used_exports": [
        "FILL_SWATCHES",
        "STROKE_SWATCHES"
      ],
      "unused_exports": [
        "InspectorSwatch"
      ],
      "type_exports": [
        "InspectorSwatch"
      ]
    },
    {
      "kind": "component",
      "name": "Inspector",
      "source": "components/whiteboard/inspector.tsx",
      "import_path": "@/components/whiteboard/inspector",
      "barrel_export": "./whiteboard/inspector",
      "exports": [
        "Inspector",
        "InspectorProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Inspector"
      ],
      "unused_exports": [
        "InspectorProps"
      ],
      "type_exports": [
        "InspectorProps"
      ]
    },
    {
      "kind": "component",
      "name": "LibraryPanel",
      "source": "components/whiteboard/library-panel.tsx",
      "import_path": "@/components/whiteboard/library-panel",
      "barrel_export": "./whiteboard/library-panel",
      "exports": [
        "LibraryPanel"
      ],
      "default_export_name": null,
      "used_exports": [
        "LibraryPanel"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "MeasurementPanel",
      "source": "components/whiteboard/measurement-panel.tsx",
      "import_path": "@/components/whiteboard/measurement-panel",
      "barrel_export": "./whiteboard/measurement-panel",
      "exports": [
        "MeasurementPanel",
        "MeasurementPanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "MeasurementPanel"
      ],
      "unused_exports": [
        "MeasurementPanelProps"
      ],
      "type_exports": [
        "MeasurementPanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "MinimapPanel",
      "source": "components/whiteboard/minimap-panel.tsx",
      "import_path": "@/components/whiteboard/minimap-panel",
      "barrel_export": "./whiteboard/minimap-panel",
      "exports": [
        "MinimapPanel",
        "MinimapPanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "MinimapPanel"
      ],
      "unused_exports": [
        "MinimapPanelProps"
      ],
      "type_exports": [
        "MinimapPanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "NumberField",
      "source": "components/whiteboard/number-field.tsx",
      "import_path": "@/components/whiteboard/number-field",
      "barrel_export": "./whiteboard/number-field",
      "exports": [
        "NumberField",
        "NumberFieldProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "NumberField"
      ],
      "unused_exports": [
        "NumberFieldProps"
      ],
      "type_exports": [
        "NumberFieldProps"
      ]
    },
    {
      "kind": "component",
      "name": "OutlinePanel",
      "source": "components/whiteboard/outline-panel.tsx",
      "import_path": "@/components/whiteboard/outline-panel",
      "barrel_export": "./whiteboard/outline-panel",
      "exports": [
        "OutlinePanel",
        "OutlinePanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "OutlinePanel"
      ],
      "unused_exports": [
        "OutlinePanelProps"
      ],
      "type_exports": [
        "OutlinePanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "PresentationPanel",
      "source": "components/whiteboard/presentation-panel.tsx",
      "import_path": "@/components/whiteboard/presentation-panel",
      "barrel_export": "./whiteboard/presentation-panel",
      "exports": [
        "PresentationPanel",
        "PresentationPanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "PresentationPanel"
      ],
      "unused_exports": [
        "PresentationPanelProps"
      ],
      "type_exports": [
        "PresentationPanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "SharePanel",
      "source": "components/whiteboard/share-panel.tsx",
      "import_path": "@/components/whiteboard/share-panel",
      "barrel_export": "./whiteboard/share-panel",
      "exports": [
        "SharePanel",
        "SharePanelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "SharePanel"
      ],
      "unused_exports": [
        "SharePanelProps"
      ],
      "type_exports": [
        "SharePanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "StatusBar",
      "source": "components/whiteboard/status-bar.tsx",
      "import_path": "@/components/whiteboard/status-bar",
      "barrel_export": "./whiteboard/status-bar",
      "exports": [
        "StatusBar",
        "StatusBarProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "StatusBar"
      ],
      "unused_exports": [
        "StatusBarProps"
      ],
      "type_exports": [
        "StatusBarProps"
      ]
    },
    {
      "kind": "component",
      "name": "SvgStagePreview",
      "source": "components/whiteboard/svg-stage-preview.tsx",
      "import_path": "@/components/whiteboard/svg-stage-preview",
      "barrel_export": "./whiteboard/svg-stage-preview",
      "exports": [
        "SvgStagePreview",
        "SvgStagePreviewProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "SvgStagePreview"
      ],
      "unused_exports": [
        "SvgStagePreviewProps"
      ],
      "type_exports": [
        "SvgStagePreviewProps"
      ]
    },
    {
      "kind": "component",
      "name": "TextControls",
      "source": "components/whiteboard/text-controls.tsx",
      "import_path": "@/components/whiteboard/text-controls",
      "barrel_export": "./whiteboard/text-controls",
      "exports": [
        "TextControls",
        "TextControlsProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "TextControls"
      ],
      "unused_exports": [
        "TextControlsProps"
      ],
      "type_exports": [
        "TextControlsProps"
      ]
    },
    {
      "kind": "component",
      "name": "TextEditorOverlay",
      "source": "components/whiteboard/text-editor-overlay.tsx",
      "import_path": "@/components/whiteboard/text-editor-overlay",
      "barrel_export": "./whiteboard/text-editor-overlay",
      "exports": [
        "TextEditorOverlay"
      ],
      "default_export_name": null,
      "used_exports": [
        "TextEditorOverlay"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "DxIcon",
      "source": "components/whiteboard/toolbar.tsx",
      "import_path": "@/components/whiteboard/toolbar",
      "barrel_export": "./whiteboard/toolbar",
      "exports": [
        "DxIcon",
        "IconName",
        "Toolbar",
        "ToolbarProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "DxIcon",
        "Toolbar"
      ],
      "unused_exports": [
        "IconName",
        "ToolbarProps"
      ],
      "type_exports": [
        "IconName",
        "ToolbarProps"
      ]
    },
    {
      "kind": "component",
      "name": "WhiteboardApp",
      "source": "components/whiteboard/whiteboard-app.tsx",
      "import_path": "@/components/whiteboard/whiteboard-app",
      "barrel_export": "./whiteboard/whiteboard-app",
      "exports": [
        "WhiteboardApp"
      ],
      "default_export_name": null,
      "used_exports": [
        "WhiteboardApp"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": "./icons/icon",
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Icon",
        "IconProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "IconProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardArrowIcon",
      "source": "components/icons/whiteboard-arrow.tsx",
      "import_path": "@/components/icons/whiteboard-arrow",
      "barrel_export": null,
      "exports": [
        "WhiteboardArrowIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardArrowIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardAudioIcon",
      "source": "components/icons/whiteboard-audio.tsx",
      "import_path": "@/components/icons/whiteboard-audio",
      "barrel_export": null,
      "exports": [
        "WhiteboardAudioIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardAudioIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardDiamondIcon",
      "source": "components/icons/whiteboard-diamond.tsx",
      "import_path": "@/components/icons/whiteboard-diamond",
      "barrel_export": null,
      "exports": [
        "WhiteboardDiamondIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardDiamondIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardEllipseIcon",
      "source": "components/icons/whiteboard-ellipse.tsx",
      "import_path": "@/components/icons/whiteboard-ellipse",
      "barrel_export": null,
      "exports": [
        "WhiteboardEllipseIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardEllipseIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardFitIcon",
      "source": "components/icons/whiteboard-fit.tsx",
      "import_path": "@/components/icons/whiteboard-fit",
      "barrel_export": null,
      "exports": [
        "WhiteboardFitIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardFitIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardHandIcon",
      "source": "components/icons/whiteboard-hand.tsx",
      "import_path": "@/components/icons/whiteboard-hand",
      "barrel_export": null,
      "exports": [
        "WhiteboardHandIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardHandIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardIconsIcon",
      "source": "components/icons/whiteboard-icons.tsx",
      "import_path": "@/components/icons/whiteboard-icons",
      "barrel_export": null,
      "exports": [
        "WhiteboardIconsIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardIconsIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardImageIcon",
      "source": "components/icons/whiteboard-image.tsx",
      "import_path": "@/components/icons/whiteboard-image",
      "barrel_export": null,
      "exports": [
        "WhiteboardImageIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardImageIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardKeyboardIcon",
      "source": "components/icons/whiteboard-keyboard.tsx",
      "import_path": "@/components/icons/whiteboard-keyboard",
      "barrel_export": null,
      "exports": [
        "WhiteboardKeyboardIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardKeyboardIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardLineIcon",
      "source": "components/icons/whiteboard-line.tsx",
      "import_path": "@/components/icons/whiteboard-line",
      "barrel_export": null,
      "exports": [
        "WhiteboardLineIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardLineIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardMathIcon",
      "source": "components/icons/whiteboard-math.tsx",
      "import_path": "@/components/icons/whiteboard-math",
      "barrel_export": null,
      "exports": [
        "WhiteboardMathIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardMathIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardMoveIcon",
      "source": "components/icons/whiteboard-move.tsx",
      "import_path": "@/components/icons/whiteboard-move",
      "barrel_export": null,
      "exports": [
        "WhiteboardMoveIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardMoveIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardPanelIcon",
      "source": "components/icons/whiteboard-panel.tsx",
      "import_path": "@/components/icons/whiteboard-panel",
      "barrel_export": null,
      "exports": [
        "WhiteboardPanelIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardPanelIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardPenIcon",
      "source": "components/icons/whiteboard-pen.tsx",
      "import_path": "@/components/icons/whiteboard-pen",
      "barrel_export": null,
      "exports": [
        "WhiteboardPenIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardPenIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardRectangleIcon",
      "source": "components/icons/whiteboard-rectangle.tsx",
      "import_path": "@/components/icons/whiteboard-rectangle",
      "barrel_export": null,
      "exports": [
        "WhiteboardRectangleIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardRectangleIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardRedoIcon",
      "source": "components/icons/whiteboard-redo.tsx",
      "import_path": "@/components/icons/whiteboard-redo",
      "barrel_export": null,
      "exports": [
        "WhiteboardRedoIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardRedoIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardSelectIcon",
      "source": "components/icons/whiteboard-select.tsx",
      "import_path": "@/components/icons/whiteboard-select",
      "barrel_export": null,
      "exports": [
        "WhiteboardSelectIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardSelectIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardTableIcon",
      "source": "components/icons/whiteboard-table.tsx",
      "import_path": "@/components/icons/whiteboard-table",
      "barrel_export": null,
      "exports": [
        "WhiteboardTableIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardTableIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardTextIcon",
      "source": "components/icons/whiteboard-text.tsx",
      "import_path": "@/components/icons/whiteboard-text",
      "barrel_export": null,
      "exports": [
        "WhiteboardTextIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardTextIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardTrashIcon",
      "source": "components/icons/whiteboard-trash.tsx",
      "import_path": "@/components/icons/whiteboard-trash",
      "barrel_export": null,
      "exports": [
        "WhiteboardTrashIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardTrashIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardUndoIcon",
      "source": "components/icons/whiteboard-undo.tsx",
      "import_path": "@/components/icons/whiteboard-undo",
      "barrel_export": null,
      "exports": [
        "WhiteboardUndoIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardUndoIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardVideoIcon",
      "source": "components/icons/whiteboard-video.tsx",
      "import_path": "@/components/icons/whiteboard-video",
      "barrel_export": null,
      "exports": [
        "WhiteboardVideoIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardVideoIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardZoomInIcon",
      "source": "components/icons/whiteboard-zoom-in.tsx",
      "import_path": "@/components/icons/whiteboard-zoom-in",
      "barrel_export": null,
      "exports": [
        "WhiteboardZoomInIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardZoomInIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "WhiteboardZoomOutIcon",
      "source": "components/icons/whiteboard-zoom-out.tsx",
      "import_path": "@/components/icons/whiteboard-zoom-out",
      "barrel_export": null,
      "exports": [
        "WhiteboardZoomOutIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "WhiteboardZoomOutIcon"
      ],
      "type_exports": []
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [
    {
      "packageId": "www/whiteboard-shell",
      "source": "forge/www/whiteboard-shell",
      "importPath": "@/forge/www/whiteboard-shell",
      "exports": []
    }
  ],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:25210702b69b6d59ffcc05d6dd281d86a34bed1222637b4a2abca89a419ced2f"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
